# Ruff configuration for PEP8 and PEP257

line-length = 79
target-version = "py313"

[lint]
select = ["E", "F", "D", "I"] # PEP8, pyflakes, PEP257, import sorting

ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "D107", # Missing docstring in __init__
    "D203", # 1 blank line required before class docstring
    "D213", # Multi-line docstring summary on second line
]

exclude = ["venv", "__pycache__"]